--Creating a table with columns
create table STUDENTS_INFORMATION(
STUDENT_ID VARCHAR(150) NOT NULL PRIMARY KEY,
FIRST_NAME CHAR(10) NOT NULL,
LAST_NAME CHAR(10) NOT NULL,
GENDER CHAR(2) NOT NULL,
AGE INT NOT NULL,
COURSE CHAR(120) NOT NULL,
DURATION VARCHAR(15) NOT NULL,);

--DROP TABLE STUDENTS_INFORMATION

SELECT * FROM STUDENTS_INFORMATION

INSERT INTO STUDENTS_INFORMATION(STUDENT_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, COURSE, DURATION)
VALUES
('100', 'RASHEED','GBOLAHAN', 'M', 35, 'COMPUTER SCI', '4 YEARS'),
('101', 'RAJI','LUKMAN', 'M', 31, 'SOFTWARE ENG', '5 YEARS'),
('102', 'ADEMOLA','KOREDE', 'M', 25, 'COMPUTER EDU', '4 YEARS'),
('103', 'OLAGUNJU','SHERIFAT', 'F', 23, 'ECONOMICS', '4 YEARS'),
('104', 'OLAYIWOLA','TOMIWA', 'F', 21, 'BIOLOGY', '4 YEARS'),
('105', 'KAREEM','FATAI', 'M', 30, 'PHYSICS', '3 YEARS'),
('106', 'OLAJIRE','AYODEJI', 'M', 21, 'AGRIC ENG', '5 YEARS'),
('107', 'HADAM','FOLORUNSHO', 'M', 33, 'COMMUNITY HTH', '5 YEARS'),
('108', 'MALEEK','FAWAZ', 'M', 33, 'BUS ADMIN', '4 YEARS'),
('109', 'RASHEED','OPEYEMI', 'M', 35, 'COMPUTER SCI', '4 YEARS');

create table STUDENT_ADDITIONAL(
STUDENT_ID VARCHAR(100) NOT NULL PRIMARY KEY,
CITY CHAR(10) NOT NULL,
TEST_RESULT INT NOT NULL,
EXAM_RESULT INT NOT NULL);

SELECT * FROM STUDENT_ADDITIONAL

INSERT INTO STUDENT_ADDITIONAL(STUDENT_ID, CITY, TEST_RESULT, EXAM_RESULT)VALUES
(100, 'IBADAN', 20, 45),
(101, 'OSOGBO', 10, 35),
(102, 'OYO', 20, 45),
(103, 'ABUJA', 14, 55),
(104, 'OGBOMOSHO', 20, 35),
(105, 'KANO',16, 45),
(106, 'LAGOS', 10, 45),
(107, 'JOS', 22, 35),
(108, 'BAUCHI', 21, 50),
(109, 'IBADAN', 25, 35);

SELECT * FROM STUDENT_ADDITIONAL

SELECT CITY FROM STUDENT_ADDITIONAL
